s/windows/centos6/
We don't support windows it turns out.

diff --git a/.github/workflows/ccpp.yml b/.github/workflows/ccpp.yml
--- a/.github/workflows/ccpp.yml
+++ b/.github/workflows/ccpp.yml
@@ -7,11 +7,67 @@ on:
     branches: [ master ]
 
 jobs:
-  build:
+  build-centos:
+    runs-on: ubuntu-18.04
+    container: centos6
+    steps:
+    - uses: actions/checkout@v2
+    - name: context
+      run: |
+        set -x
+        set
+        pwd
+        whoami
+        hostname || true
+        df -h || true
+        uname -a
+        gcc -v
+        cmake --version
+        ifconfig
+        curl ifconfig.me
+      continue-on-error: true
+    - name: cmake generate
+      run: |
+        mkdir antsbin
+        cd antsbin
+        cmake \
+         -DBUILD_SHARED_LIBS=ON \
+         ../
+    - name: make
+      working-directory: antsbin
+      run: |
+        make VERBOSE=1 -j 4
+      timeout-minutes: 300
+      # for debugging, don't let a crash/timeout here fail the whole build
+      # (github CI seems glitchy about giving reliable output about what happened on timeouts)
+      continue-on-error: true
+    - name: pre-package
+      run: |
+        mkdir fakeroot/
+        cd antsbin/ANTS-build
+        make VERBOSE=1 -j 4 DESTDIR="../../fakeroot" install
+      continue-on-error: true
+    - name: package
+      run: |
+        # snip out the apps we need for https://github.com/neuropoly/spinalcordtoolbox, since including all of ANTS is too much
+        mkdir sct-apps/
+        cp antsbin/ANTS-build/Examples/{antsRegistration,antsSliceRegularizedRegistration,antsApplyTransforms,ComposeMultiTransform} sct-apps
+        (cd sct-apps; for i in `ls`; do mv $i isct_$i; done)
+        tar -zcvf sct-apps.tar.gz sct-apps/
+      continue-on-error: true
+    - name: results (DEBUG)
+      run: find .
+    - name: Upload result
+      uses: actions/upload-artifact@v2-preview
+      with:
+        name: ants-superbuild
+        #path: fakeroot/ # this is 2.3G large in this build
+        path: sct-apps.tar.gz
 
+  build:
     strategy:
       matrix:
-        os: [ubuntu-16.04, ubuntu-18.04, macos-latest, windows-latest]
+        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
     runs-on: ${{ matrix.os }}
     steps:
     - uses: actions/checkout@v2
